### PR TITLE
Create jquery.countdown-kk.js

### PR DESCRIPTION
**Pull request by grimalschi**
Kazakh translation

### CODE REVIEW

**Comment by kbwood** [comment]
Hi Veaceslav, according to Wikipedia, the code for the Kazakh language is 'kk' (https://en.wikipedia.org/wiki/Kazakh_language). In the comment in the file you say its the Georgian localisation, not Kazakh - which is correct? Are different terms used for only one year/month/etc. (labels1 field) ?

**Comment by grimalschi** [comment]
Hello! I used "kz" because of ".kz" domain name: https://en.wikipedia.org/wiki/.kz

Changed to "kk".

"Kazakh" is correct, "Georgian" is my mistake. Fixed this.

There is no different terms for label1 and label2. You can see example of another countdown script here: https://biznes-bastau.kz (near footer)

Personally I don't speak Kazakh, but my friend is native. He confirmed that there is only one term.

**Comment by grimalschi** [comment]
Let's merge?

**Comment by kbwood** [comment]
I added the file a month ago.

**Pull request closed without merging**
